### ISSUE TITLE
Current name is the same as http://locate32.cogit.net/, needs its own name to prevent confusion

### ISSUE THREAD

**Issue by zaggynl** [zaggynl/locate32#5]
Suggestions?
So far I have:
~~qlocate~~  already taken: http://qt-apps.org/content/show.php?content=125973
locate-frontend

**Comment by zaggynl** [comment]
qlocate already taken: http://qt-apps.org/content/show.php?content=125973

**Comment by worzel666** [comment]
glocate? pylocate?

**Comment by zaggynl** [comment]
pyLocate32: https://github.com/zaggynl/pyLocate32
